services:
  - type: web
    name: steel-defect-detector
    env: python
    plan: free
    buildCommand: |
      echo "python-3.10.13" > runtime.txt
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
